### ISSUE TITLE
log aggregation and UI

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#30]
I've been investigating potential ways to aggregate and search our logs.

The one I like best so far is [elasticsearch](http://www.elasticsearch.org) as our log database, with [kibana](http://three.kibana.org) as the UI.

The recommended way to fill elasticsearch is with logstash. I think we should initially use it, but also try to use heka and write a plugin for elasticsearch output.

I also looked at [graylog2](http://graylog2.org), [logstash](http://logstash.net) (only), [fluentd](http://fluentd.org), [openTSDB](http://opentsdb.net/)

graylog2
- seems ok, has more dependencies than others
  - depends on mongodb and elasticsearch
- more complicated / less flexible than others
- decent UI

logstash
- many of the same features as heka
- embedded elasticsearch
- rudimentary search, kibana is nicer

fluentd
- many of the same features as heka
- no UI

openTSDB
- probably better as a metric database
- depends on HBase
- may be useful in the future
## Proposal

I'd like to set up an awsboxen elasticsearch cluster with the kibana UI and use logstash tail log files written by the application to populate the database.
### Tasks
- [x] Create an elasticsearch ami
- [x] Create an awsboxen profile
- [x] Install and configure an awsbox for kibana
- [x] Configure the idp to write logs to a file in json format
- [x] Install and configure logstash on the idp ami
- [ ] Write an elasticsearch plugin for heka
